#cloud-config
users:
  # Create user with sudo privileges
  - name: matt
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    # Authorized keys (public SSH keys) for the user 
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUhMn1/qjoLLPTaj973UB1YBA8tdgRgCZFXEa+XxI66 matt@mattndr
packages:
  - ntp
  - fail2ban
  - apparmor
  - apparmor-utils
package_update: true
package_upgrade: false
runcmd:
# https://community.hetzner.com/tutorials/securing-ssh
  - cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
  - sed -i -e '/^\[sshd\]/s/^.*$/\[sshd\]\n\nenabled = true\nbanaction = iptables-multiport/' /etc/fail2ban/jail.local
  - sed -i -e 's/= ssh/= 22/g' /etc/fail2ban/jail.local
  - systemctl restart fail2ban
  - sed -i -e '/^#ClientAliveInterval/s/^.*$/ClientAliveInterval 300/' /etc/ssh/sshd_config
  - sed -i -e '/^#ClientAliveCountMax/s/^.*$/ClientAliveCountMax 1/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
# Change default port for SSH (you also need to change the port specified in /etc/fail2ban/jail.local)
# - sed -i 's/[#]*Port 22/Port 4422/g' /etc/ssh/sshd_config
# Disables remote GUI view
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
# Disables port forwarding
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
# Disables the forwarding of the SSH login
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
# Only selected users are allowed to establish an SSH connection to the server
  - sed -i '$a AllowUsers matt' /etc/ssh/sshd_config
# Apply changes
  - systemctl restart sshd
# Switch to new user
  - su - matt
# Join the RKE2 cluster
  - 
