#cloud-config
users:
  - name: matt
    groups: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: $6$Xb0trHnV7gPgv$CLcddQ.UYU/0RoOsbApbLEBKT1dd2PwMNyTo0c0EHA/aVnDsejBlN1MvNuEYL/WOjhOiHQZa6K676/sG945.R.
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINzgVPYTCTMDsx9TtHxXEpTtHWn3e7oTbOl7bhHNH/1a matt@mattndr
packages:
  - fail2ban
package_update: true
package_upgrade: false
runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 20/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers matt' /etc/ssh/sshd_config
  - reboot
